name: r_to_python
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.7.5
  - certifi=2021.5.30
  - cycler=0.10.0
  - decorator=5.0.9
  - fonttools=4.25.0
  - freetype=2.10.4
  - intel-openmp=2021.3.0
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jpeg=9b
  - kiwisolver=1.3.1
  - lcms2=2.12
  - libcxx=12.0.0
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandas=1.3.2
  - parso=0.8.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - prompt-toolkit=3.0.17
  - ptyprocess=0.7.0
  - pygments=2.10.0
  - pyparsing=2.4.7
  - python=3.9.6
  - python-dateutil=2.8.2
  - pytz=2021.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - tzdata=2021a
  - wcwidth=0.2.5
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9